apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-p
spec:
  selector:
    matchLabels:
      app: shell
      env: p
  replicas: 1
  template:
    metadata:
      labels:
        app: shell
        env: p
    spec:
      containers:
      - image: trayla/shell:0.0.1
        name: shell
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always
