platform:

  assets:
    kubernetes:
      # apt-cache madison kubeadm | head -n 1
      version: 1.23.1-00
    calico:
      # https://projectcalico.docs.tigera.io/release-notes/
      version: 3.21
    istio:
      # https://istio.io/latest/docs/releases/supported-releases/
      version: 1.12
    nginx:
      # helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update && helm search repo ingress-nginx/ingress-nginx --v>
      version: 4.0.13
    certmanager:
      # https://cert-manager.io/docs/release-notes/
      version: 1.6.1
    prometheus:
      # https://github.com/prometheus-community/helm-charts/releases
      version: 27.2.0
    longhorn:
      # https://github.com/longhorn/longhorn/releases
      version: 1.2.3
    metallb:
      # https://metallb.universe.tf/release-notes/
      version: 0.11.0
    stern:
      # https://github.com/wercker/stern/releases
      version: 1.11.0

  # Your domain, the platform should be reachable through
  domain: <<your.domain>>

  # The name of the TOP instance
  name: top1

  # The default Email address to be used by the platform
  email: <<your.email@your.domain>>

  # The default administration user account
  admin:
    password: <<secretpassword>>

  # The console
  console:
    ip: <<ip>>

  # The platform nodes
  nodes:
    masters:
    - ip: <<ip>>
    workers:
    - ip: <<ip>>

  # The storage settings
  storage:
    backup:
      s3:
        bucket: <<yours3bucket>>
        region: <<yours3region>>
        access_key_id: <<yours3accesskey>>
        secret_access_key: <<yours3secretaccesskey>>
        endpoints: <<yours3endpoints>>

  certissuer:
    # production or staging
    default: staging

custom:

  # Custom Kubernetes namespaces to be created upon installation
  namespaces:
  #  - name: myns
