platform:

  assets:
    k3s:
      # https://github.com/k3s-io/k3s/releases
      version: v1.24.8+k3s1
    calico:
      # https://projectcalico.docs.tigera.io/release-notes/
      version: 3.24.5
    istio:
      # https://istio.io/latest/docs/releases/supported-releases/
      version: 1.16
    nginx:
      # helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update && helm search repo ingress-nginx/ingress-nginx --versions | head -n 2
      version: 4.4.0
    certmanager:
      # https://cert-manager.io/docs/release-notes/
      version: 1.10.0
    prometheus:
      # https://github.com/prometheus-community/helm-charts/releases
      version: 42.1.1
    longhorn:
      # https://github.com/longhorn/longhorn/releases
      version: 1.3.2
    metallb:
      # https://metallb.universe.tf/release-notes/
      version: 0.13.7
    stern:
      # https://github.com/stern/stern/releases
      version: 1.22.0

  # Your domain, the platform should be reachable through
  domain: <domain-name>

  # The name of the TOP instance
  name: <instance-name>

  # The default Email address to be used by the platform
  email: <email>

  # The default administration user account
  admin:
    password: <password>

  # Load balancer settings
  public:
    ip: <public-ip-address>

  # The platform nodes
  nodes:
    controlplanes:
      controlplane1:
        hostname: controlplane1
        ip: <internal-ip-address>
    workers:
      worker01:
        hostname: worker01
        ip: <internal-ip-address>
      worker02:
        hostname: worker02
        ip: <internal-ip-address>

  # The storage settings
  storage:
    backup:
      s3:
        bucket: <bucket>
        region: <region>
        access_key_id: <access-key>
        secret_access_key: <secret-key>
        endpoints: <endpoint-url>

  certissuer:
    # production or staging
    default: staging

custom:

  # Custom Kubernetes namespaces to be created upon installation
  namespaces:
  # - name: <namespace-name>
