- hosts: all
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Disable Swap files because these are not supported on Docker hosts

  - name: Remove swapfile from /etc/fstab
    mount:
      path: none
      fstype: swap
      state: absent
    when: allhosts == 'true' or inventory_hostname == host

  - name: Disable swap
    command: swapoff -a

  # Install Docker

  - name: Install Docker
    apt:
      name: docker.io
      state: present
      update_cache: true
    when: allhosts == 'true' or inventory_hostname == host

  # Change the Docker driver to SystemD

  - name: change the Docker driver to SystemD
    shell: |
      cat <<EOF > /etc/docker/daemon.json
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }
      EOF
      systemctl daemon-reload && systemctl restart docker
