- hosts: kubernetes
  become: yes
  vars_files:
    - /opt/mgmt/values-top.yaml
  tasks:

  - name: Add IP address of all control plane nodes to each Kubernetes node
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ item.ip.int }} {{ item.hostname }}"
      state: present
    loop: "{{ platform.nodes.controlplanes.values() | list }}"

  - name: Add IP address of all worker nodes to each Kubernetes node
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ item.ip.int }} {{ item.hostname }}"
      state: present
    loop: "{{ platform.nodes.workers.values() | list }}"
