- hosts: console
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  - name: Determine the dynamic HTTP port of the Nginx service
    shell: kubectl -n top get svc ingress-nginx-controller -o jsonpath='{.spec.ports[0].nodePort}'
    register: nginx_port_http

  - name: Determine the dynamic HTTPS port of the Nginx service
    shell: kubectl -n top get svc ingress-nginx-controller -o jsonpath='{.spec.ports[1].nodePort}'
    register: nginx_port_https

  - name: Show the ports of the Nginx service
    debug:
      msg: 'Nginx ports: http={{ nginx_port_http.stdout }}, https={{ nginx_port_https.stdout }}'

  - name: Store the NGINX ports
    set_fact:
      nginx_port_http: "{{ nginx_port_http.stdout }}"
      nginx_port_https: "{{ nginx_port_https.stdout }}"

- hosts: master01
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Add port forwardings to the Ingress from the outside world

  - name: "Create port forwarding of http host port to node port {{ hostvars['console'].nginx_port_http }}"
    iptables:
      table: nat
      chain: PREROUTING
      protocol: tcp
      destination_port: 80
      jump: REDIRECT
      to_ports: "{{ hostvars['console'].nginx_port_http }}"

  - name: "Create port forwarding of http host port to node port {{ hostvars['console'].nginx_port_https }}"
    iptables:
      table: nat
      chain: PREROUTING
      protocol: tcp
      destination_port: 443
      jump: REDIRECT
      to_ports: "{{ hostvars['console'].nginx_port_https }}"
