- hosts: controlplane1
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Initialize the K3S cluster

  - name: Initialize the K3S cluster
    shell: |
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_TOKEN="token" INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" INSTALL_K3S_VERSION="{{ platform.assets.k3s.version }}" sh -s - server --cluster-init
      mkdir -p /root/.kube && kubectl config view --raw > ~/.kube/config
      
  # Install Stern for enhanced log display

  - name: Install Stern
    get_url:
      url: https://github.com/stern/stern/releases/download/v{{ platform.assets.stern.version }}/stern_{{ platform.assets.stern.version }}_linux_amd64.tar.gz
      dest: /usr/bin/stern
      mode: '0001'
