- hosts: workers
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Install Longhorn requirements on each data node

  - name: Create the longhorn data directory
    file:
      path: /var/lib/longhorn
      state: directory
    when: allhosts == 'true' or inventory_hostname == host

  - name: Install iSCSI packages for Longhorn
    apt:
      name: open-iscsi
      state: present
    when: allhosts == 'true' or inventory_hostname == host

  - name: Install NFS tools for Longhorn
    apt:
      name: nfs-common
      state: present
    when: allhosts == 'true' or inventory_hostname == host

  # Install K3S on the worker node

  - name: Install K3S on the worker node
    shell: |
      curl -sfL https://get.k3s.io | K3S_URL="https://controlplane1:6443" K3S_TOKEN="{{ platform.admin.password }}" sh -

  - name: Add IP address of all control plane nodes to each worker node
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ item.ip }} {{ item.hostname }}"
      state: present
    loop: "{{ platform.nodes.controlplanes.values() | list }}"

  - name: Add IP address of all worker nodes to each worker node
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ item.ip }} {{ item.hostname }}"
      state: present
    loop: "{{ platform.nodes.workers.values() | list }}"
