- hosts: kubernetes
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  - name: Set the hostname of all Kubernetes nodes
    ansible.builtin.hostname:
      name: "{{ hostvars[inventory_hostname].ansible_fqcn }}"

  # Enable IPv4 forwarding

  - name: Enable IP forwarding
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes

  - name: Enable IPv6 forwarding
    ansible.posix.sysctl:
      name: net.ipv6.conf.all.forwarding
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes

  # Ensure the existance of the netfilter bridging module

  - name: Ensure the existance of the netfilter bridging module
    shell: modprobe br_netfilter
