- hosts: console
  become: yes
  vars_files:
    - /opt/mgmt/values-top.yaml
  tasks:

    # Install the Calico SDN alongside the command line interface

    - name: Install Calico SDN
      become: yes
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ platform.assets.calico.version }}/manifests/tigera-operator.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v{{ platform.assets.calico.version }}/manifests/custom-resources.yaml
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Install the Calico command line interface
      shell: |
        kubectl create -f https://projectcalico.docs.tigera.io/archive/v{{ platform.assets.calico.version }}/manifests/calicoctl.yaml

    - name: Define a shell alias for calicoctl for root
      lineinfile:
        path=/root/.bashrc
        line="alias calicoctl='kubectl exec -i -n kube-system calicoctl /calicoctl -- '"
        owner=root
        regexp="^alias calicoctl='kubectl exec -i -n kube-system calicoctl /calicoctl -- '$"
        state=present
        insertafter=EOF
        create=True

    - name: Sleep some time and hope Calico has come up
      ansible.builtin.wait_for:
        timeout: 120

    # Install the Helm package manager

    - name: Download the Helm package manager
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get-helm.sh
        mode: '0700'

    - name: Install Helm
      shell: /tmp/get-helm.sh

    - name: Install the Stable Helm repository
      shell: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo update

    # Install the base components

    - name: Create the base namespace
      shell: kubectl create namespace top

    - name: Create the Docker Registry pull secret inside all custom namespaces
      shell: "kubectl create -n top secret generic admin-password --from-literal=admin-user=admin --from-literal=admin-password={{ platform.admin.password }}"
