- hosts: controlplane1
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Install the MetalLB load balancer
  
  - name: Create the MetalLB namespace
    shell: |
      kubectl create ns metallb-system

  - name: Install the MetalLB load balancer
    shell: |
      helm repo add metallb https://metallb.github.io/metallb
      helm install metallb metallb/metallb \
        --namespace metallb-system \
        --version {{ platform.assets.metallb.version }}

  - name: Apply the load balancer configuration
    shell: |
      cat <<EOF | kubectl create -f -
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - {{ platform.public.ip }}/32
      EOF
