- hosts: controlplane1
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Install the MetalLB load balancer

  - name: Install the MetalLB load balancer
    shell: |
      helm repo add metallb https://metallb.github.io/metallb
      helm install metallb metallb/metallb \
        --namespace top \
        --version {{ platform.assets.metallb.version }}
