- hosts: controlplane1
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Initialize the K3S cluster

  - name: Initialize the K3S cluster
    shell: |
      curl -sfL https://get.k3s.io | \
        K3S_KUBECONFIG_MODE="644" \
        K3S_TOKEN="{{ platform.admin.password }}" \
        INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" \
        INSTALL_K3S_VERSION="{{ platform.assets.k3s.version }}" \
        sh -s - server --cluster-init
    register: results

  - ansible.builtin.debug:
      msg: "{{ results.stdout_lines }}"

  - name: Store the local Kubernetes configuration
    shell: |
      mkdir -p /root/.kube && kubectl config view --raw > ~/.kube/config

  - name: Enable shell completion for the root user
    shell: |
      kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
      k3s completion bash | sudo tee /etc/bash_completion.d/k3s > /dev/null

- hosts: controlplane1
  become: no
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  - name: Install Krew, the Kubectl package manager
    shell: |
      (
        set -x; cd "$(mktemp -d)" &&
        OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
        ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
        KREW="krew-${OS}_${ARCH}" &&
        curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
        tar zxvf "${KREW}.tar.gz" &&
        ./"${KREW}" install krew
      )

  - name: Modify the bashrc to include Krew
    blockinfile:
      dest: "~/.bashrc"
      block: |
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        export KUBE_EDITOR=nano
      marker: '# {mark} ANSIBLE MANAGED BLOCK'
      insertbefore: BOF
      create: yes

  - name: Install stern, a log aggregator for Kubectl
    shell: |
      kubectl krew install stern

  # Ensure bash-completion is installed (Debian/Ubuntu; change for your distro)
  - name: Install bash-completion
    apt:
      name: bash-completion
      state: present
    become: yes

  # System-wide kubectl completion file (you already have it; this keeps it idempotent)
  - name: Ensure kubectl completion exists system-wide
    shell: kubectl completion bash | tee /etc/bash_completion.d/kubectl >/dev/null
    args:
      executable: /bin/bash
      creates: /etc/bash_completion.d/kubectl
    become: yes

  # Per-user shell init
  - name: Ensure ~/.bashrc wires bash-completion + kubectl + alias k
    blockinfile:
      dest: "{{ ansible_env.HOME }}/.bashrc"
      create: yes
      insertbefore: BOF
      marker: "# {mark} ANSIBLE MANAGED K8S BLOCK"
      block: |
        # Load bash-completion
        if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
        fi

        # kubectl completion (prefer system file; fallback to dynamic)
        if command -v kubectl >/dev/null 2>&1; then
          if [ -f /etc/bash_completion.d/kubectl ]; then
            . /etc/bash_completion.d/kubectl
          else
            source <(kubectl completion bash)
          fi
          alias k=kubectl
          complete -o default -F __start_kubectl k
        fi

  - name: Ensure login shells read ~/.bashrc
    lineinfile:
      path: "{{ ansible_env.HOME }}/.bash_profile"
      line: '[ -f ~/.bashrc ] && . ~/.bashrc'
      create: yes
