- hosts: console
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Install Prometheus

  - name: Install Prometheus
    shell: |
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update
      helm install prometheus prometheus-community/kube-prometheus-stack \
        --namespace top \
        --version {{ platform.assets.prometheus.version }} \
        --values /opt/mgmt/top/kubernetes/monitoring/values.yaml \
        --set prometheus.ingress.hosts[0]=prometheus.top.{{ platform.domain }} \
        --set prometheus.ingress.tls[0].hosts[0]=prometheus.top.{{ platform.domain }} \
        --set alertmanager.ingress.hosts[0]=alertmanager.top.{{ platform.domain }} \
        --set alertmanager.ingress.tls[0].hosts[0]=alertmanager.top.{{ platform.domain }} \
        --set grafana.ingress.hosts[0]=grafana.top.{{ platform.domain }} \
        --set grafana.ingress.tls[0].hosts[0]=grafana.top.{{ platform.domain }} \
        --set grafana.ingress.adminPassword={{ platform.admin.password }}
