- hosts: controlplane1
  become: yes
  vars_files:
  - /opt/mgmt/values-top.yaml
  tasks:

  # Install the MetalLB load balancer
  
  - name: Create the MetalLB namespace
    shell: |
      kubectl create ns metallb-system

  - name: Install the MetalLB load balancer
    shell: |
      helm repo add metallb https://metallb.github.io/metallb
      helm install metallb metallb/metallb \
        --namespace top \
        --version {{ platform.assets.metallb.version }}

  - name: Apply the load balancer configuration
    shell: |
      cat <<EOF | kubectl create -f -
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default
        namespace: top
      spec:
        addresses:
        - {{ platform.public.ip }}/32
      EOF
